//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelMath
{
    public partial class Admin_Quizzes
    {
        /// <summary>
        /// PanelMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel
            PanelMessage;

        /// <summary>
        /// LblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label
            LblMessage;

        /// <summary>
        /// TxtQuizSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox
            TxtQuizSearch;

        /// <summary>
        /// DdlClassFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList
            DdlClassFilter;

        /// <summary>
        /// BtnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button
            BtnSearch;

        /// <summary>
        /// RepeatQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater
            RepeatQuizzes;

        /// <summary>
        /// PanelNoQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel
            PanelNoQuizzes;
    }
}