//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelMath
{


    public partial class Admin_Dashboard
    {

        /// <summary>
        /// LblTotalStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalStudents;

        /// <summary>
        /// LblTotalLecturers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalLecturers;

        /// <summary>
        /// LblTotalClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalClasses;

        /// <summary>
        /// LblTotalQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalQuizzes;

        /// <summary>
        /// RepeatRecentUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeatRecentUsers;

        /// <summary>
        /// PanelNoRecentUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelNoRecentUsers;
    }
}
