//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelMath
{


    public partial class Admin_Classes
    {

        /// <summary>
        /// PanelMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelMessage;

        /// <summary>
        /// LblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblMessage;

        /// <summary>
        /// PanelClassForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelClassForm;

        /// <summary>
        /// LblFormTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblFormTitle;

        /// <summary>
        /// HiddenClassId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField HiddenClassId;

        /// <summary>
        /// TxtClassName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtClassName;

        /// <summary>
        /// ReqClassName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator ReqClassName;

        /// <summary>
        /// TxtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtDescription;

        /// <summary>
        /// BtnSaveClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnSaveClass;

        /// <summary>
        /// BtnCancelForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCancelForm;

        /// <summary>
        /// PanelEnrolment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelEnrolment;

        /// <summary>
        /// LblEnrolClassName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblEnrolClassName;

        /// <summary>
        /// BtnCloseEnrolment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCloseEnrolment;

        /// <summary>
        /// HiddenEnrolClassId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField HiddenEnrolClassId;

        /// <summary>
        /// DdlAddStudent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList DdlAddStudent;

        /// <summary>
        /// BtnAddStudentToClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnAddStudentToClass;

        /// <summary>
        /// RepeatEnrolledStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeatEnrolledStudents;

        /// <summary>
        /// PanelNoEnrolled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelNoEnrolled;

        /// <summary>
        /// BtnAddClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnAddClass;

        /// <summary>
        /// RepeatClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeatClasses;

        /// <summary>
        /// PanelNoClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelNoClasses;
    }
}
