//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelMath
{
    public partial class Admin_Announcements
    {
        protected global::System.Web.UI.WebControls.Panel
            PanelMessage;

        protected global::System.Web.UI.WebControls.Label
            LblMessage;

        protected global::System.Web.UI.WebControls.Label
            LblFormTitle;

        protected global::System.Web.UI.WebControls.HiddenField
            HiddenAnnouncementId;

        protected global::System.Web.UI.WebControls.ValidationSummary
            AnnouncementValidationSummary;

        protected global::System.Web.UI.WebControls.TextBox
            TxtTitle;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator
            ReqTitle;

        protected global::System.Web.UI.WebControls.DropDownList
            DdlTargetClass;

        protected global::System.Web.UI.WebControls.DropDownList
            DdlStatus;

        protected global::System.Web.UI.WebControls.TextBox
            TxtMessage;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator
            ReqMessage;

        protected global::System.Web.UI.WebControls.Button
            BtnCancelEdit;

        protected global::System.Web.UI.WebControls.Button
            BtnSaveAnnouncement;

        protected global::System.Web.UI.WebControls.TextBox
            TxtSearch;

        protected global::System.Web.UI.WebControls.DropDownList
            DdlClassFilter;

        protected global::System.Web.UI.WebControls.DropDownList
            DdlStatusFilter;

        protected global::System.Web.UI.WebControls.Button
            BtnSearch;

        protected global::System.Web.UI.WebControls.Repeater
            RepeatAnnouncements;

        protected global::System.Web.UI.WebControls.Panel
            PanelNoAnnouncements;
    }
}