//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelMath
{


    public partial class Admin_Users
    {

        /// <summary>
        /// PanelMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelMessage;

        /// <summary>
        /// LblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblMessage;

        /// <summary>
        /// PanelUserForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelUserForm;

        /// <summary>
        /// LblFormTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblFormTitle;

        /// <summary>
        /// HiddenUserId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField HiddenUserId;

        /// <summary>
        /// TxtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtFullName;

        /// <summary>
        /// ReqFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator ReqFullName;

        /// <summary>
        /// TxtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtEmail;

        /// <summary>
        /// ReqEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator ReqEmail;

        /// <summary>
        /// RegexEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegexEmail;

        /// <summary>
        /// DdlRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList DdlRole;

        /// <summary>
        /// FormLevelField control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FormLevelField;

        /// <summary>
        /// TxtForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtForm;

        /// <summary>
        /// LblPasswordHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblPasswordHint;

        /// <summary>
        /// TxtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtPassword;

        /// <summary>
        /// LblPasswordEditHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblPasswordEditHint;

        /// <summary>
        /// BtnSaveUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnSaveUser;

        /// <summary>
        /// BtnCancelForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCancelForm;

        /// <summary>
        /// TxtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtSearch;

        /// <summary>
        /// DdlRoleFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList DdlRoleFilter;

        /// <summary>
        /// BtnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnSearch;

        /// <summary>
        /// BtnAddUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnAddUser;

        /// <summary>
        /// RepeatUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeatUsers;

        /// <summary>
        /// PanelNoUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PanelNoUsers;
    }
}
