//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelMath
{
    public partial class Admin_Activity_Logs
    {
        protected global::System.Web.UI.WebControls.Panel
            PanelMessage;

        protected global::System.Web.UI.WebControls.Label
            LblMessage;

        protected global::System.Web.UI.WebControls.TextBox
            TxtSearch;

        protected global::System.Web.UI.WebControls.DropDownList
            DdlActionFilter;

        protected global::System.Web.UI.WebControls.DropDownList
            DdlEntityFilter;

        protected global::System.Web.UI.WebControls.Button
            BtnSearch;

        protected global::System.Web.UI.WebControls.Repeater
            RepeatActivityLogs;

        protected global::System.Web.UI.WebControls.Panel
            PanelNoLogs;
    }
}